num1 = input("enter first number: ")
num2 = input("enter second number: ")
num3 = input("enter third number: ")
num4 = input("enter fourth number: ")
answer = int(num1) + int(num2) + int(num3) + int(num4)
print("answer: " + str(answer/4))
